django_random_word_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('random_words_app.urls')),
    path('admin/', admin.site.urls),
]

random_words_app/urls.py
from django.urls import path
from . import views

app_name = 'random_words_app'

urlpatterns = [
    path('', views.index, name='home'),
    path('random', views.random, name='random'),
    path('reset', views.reset, name='reset'),
]

random_words_app/models.py
from django.db import models

# Create your models here.

random_words_app/views.py
from django.shortcuts import render, HttpResponse
from django.utils.crypto import get_random_string

# Create your views here.

def index(request):
    request.session["random_count"] = 0
    return render(request, 'random_words_app/index.html')

def random(request):
    word = get_random_string(length=14)
    context = {
        'random_words_app':word
    }
    request.session["random_count"] += 1
    return render(request, 'random_words_app/index.html', context)

def reset(request):
    request.session["random_count"] = 0
    return render(request, 'random_words_app/index.html')

random_words_app/templates/random_words_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-CL">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Base template plantilla Django Bootstrap JQuery JS">
    <meta name="author" content="Ronald Guerrero 0071">
    <meta name="keywords" content="homework">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% comment %}
	<!-- Mi CSS-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Mis JS-->
    
	{% endcomment %}
</head>
<body>
    <div class="wrapper">
        
        <div class="container-fluid p-5 bg-light">
            {% block content %}{% endblock %}
        </div>
    </div>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

random_words_app/templates/random_words_app/index.html
{% extends 'random_words_app/base.html' %}

{% load static %}
{% block css_app %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block title %}Random Words APP{% endblock %}

{% block content %}
<div class="container mt-4 text-center">
    <h3>Random Words APP (attemp #{{request.session.random_count}})</h3>
    <h1>{{random_words_app}}</h1>
    <a class="btn btn-secondary m-5" href="{% url 'random_words_app:random' %}">Generate</a>
    <a class="btn btn-secondary m-5" href="{% url 'random_words_app:reset' %}">Reset</a>
</div>
{% endblock %}